spring:
  application:
    name: adg-rule
  profiles:
    active: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  config:
    expected_quantity: 2000000  #预期规则数量
    fault_tolerance: 0.001 #容错率
    warn_limit: 7 #警告阈值, 规则长度小于该值时会输出警告日志
    batch_size: 10000 #写入文件的批次大小

  # 规则源配置，remote为远程规则，local为本地规则，支持多个规则源
  rule:

    # 仅支持 http/https，不限定响应内容格式
    remote:
#      - name: 'example rule' #规则名称
#        path: 'https://example.org/rule.txt' #规则地址
#      - 'https://example.org/rule2.txt' #旧版写法, 不推荐
     - name: 'AdGuard DNS filter' #规则名称
       path: 'https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt' #规则地址
     - name: '广告终结者' #规则名称
       path: 'http://sub.adtchrome.com/adt-chinalist-easylist.txt' #规则地址
     - name: 'EasyList' #规则名称
       path: 'https://easylist-downloads.adblockplus.org/easylist.txt' #规则地址
     - name: 'EasyList China' #规则名称
       path: 'https://easylist-downloads.adblockplus.org/easylistchina.txt' #规则地址
     - name: 'example rule' #规则名称
       path: 'https://example.org/rule.txt' #规则地址
     - name: 'anti-AD' #规则名称
       path: 'https://anti-ad.net/easylist.txt' #规则地址
     - name: 'Adaway HOST' #规则名称
       path: 'https://adaway.org/hosts.txt' #规则地址
     - name: 'adblock_auto' #规则名称
       path: 'https://raw.gitmirror.com/lingeringsound/adblock_auto/main/Rules/adblock_auto.txt' #规则地址
     - name: 'NeoHosts' #规则名称
       path: 'https://neodev.team/adblocker' #规则地址
     - name: 'catsHosts' #规则名称
       path: 'https://jihulab.com/cats-team/adrules/-/raw/main/hosts.txt' #规则地址
     - name: '轻量规则' #规则名称
       path: 'https://ghproxy.com/https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt' #规则地址
     - name: 'AWA' #规则名称
       path: 'https://ghproxy.net/https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Adblock-Rule/main/AWAvenue-Adblock-Rule.txt' #规则地址
     - name: 'Github加速' #规则名称
       path: 'https://ghproxy.com/https://github.com/Potterli20/file/releases/download/github-hosts/Accelerate-Hosts.txt' #规则地址
    - name: 'Adblock Warning Removal List' #规则名称
       path: 'https://easylist-downloads.adblockplus.org/antiadblockfilters.txt' #规则地址
     - name: '1Hosts' #规则名称
       path: 'https://o0.pages.dev/Pro/adblock.txt' #规则地址

    #本地规则请将文件放置到项目路径rule目录中
    local:
#      - name: 'local rule'
#        path: 'local-rule.txt'
  output:
    file_header: |  #输出文件头, 占位符${name}将被替换为文件名，如all.txt,  ${date} 将被替换为当前日期
      [ADFS Adblock List]
      ! Title: ${name}
      ! Last Modified: ${date}
      ! Homepage: https://github.com/xuu888/ad-filters-subscriber/
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt: #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      dns.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
